### ISSUE TITLE
Is there a bug when optimizing a single image?

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/AtlasCarCalibration#106]
Running the optimization for a single image, it seems the overlay of the chessboard in the image is not perfectly aligned as it should be ...

![image](https://user-images.githubusercontent.com/11350998/71490602-79c2d700-2823-11ea-858d-c56455825f5b.png)

Strange ... there is no other sensor in the optimization, the chessboard should move freely to zero out the error

**Comment by miguelriemoliveira** [comment]
After a lot of work I was able to trace to problem down to a disparity between our function **utilities.projectToCamera** and ROS **camera.project3dToPixel** from image geometry.

Here's the output of these projections of the same points:

**utilities.projectToCamera**:
```
[[ 189.29289928  226.94824387  264.88628897  303.05462357  341.40761758
   379.90528377  418.51225394  457.19662859  495.92895792  191.53180407
   228.74563473  266.23463536  303.94827546  341.842435    379.8783298
   418.02154935  456.24096867  494.50778941  193.80733184  230.5776186
   267.61697645  304.87650229  342.31335851  379.88975771  417.57205765
   455.32973141  493.13446436  196.11624396  232.44168963  269.03134254
   305.8377066   342.81902967  379.9383436   417.16261259  454.4617576
   491.80780553  198.45637221  234.33623044  270.47649508  306.83088534
   343.35856444  380.02323123  416.79231838  453.63606752  490.52672715
   200.82638499  236.26031554  271.95176419  307.85549899  343.9314518
   380.14385828  416.46050248  452.85183946  489.29023872]
 [ 426.15803994  427.78659109  429.40377549  431.00990898  432.60521628
   434.189789    435.76354836  437.32620266  438.87721007  461.37567465
   463.06355873  464.72694626  466.36739685  467.98618979  469.58428616
   471.16229565  472.72043795  474.2585096   495.73644748  497.4809208
   499.1885064   500.86186396  502.50320542  504.11426069  505.6962482
   507.24983989  508.77513166  529.24548423  531.04490422  532.79560545
   534.5012194   536.16478183  537.78870185  539.37473582  540.92395556
   542.43672204  561.90831371  563.76191625  565.55538357  567.29320427
   568.97914085  570.61620174  572.20661821  573.75181555  575.2523897
   593.73042186  595.63813519  597.47459362  599.24504039  600.95387797
   602.60464285  604.19998517  605.74164251  607.23041926]]

```

and **camera.project3dToPixel**:

```
[[ 198.65981361  236.624796    274.56048866  312.46692269  350.3441403
   388.19215851  426.01103338  463.80078742  501.56145424  200.76783036
   238.29001124  275.7835809   313.24856931  350.68501741  388.09294124
   425.47239545  462.82340151  500.14599189  202.8273096   239.91689902
   276.97853243  314.0122387   351.01805757  387.99600417  424.94613177
   461.86846086  498.7630228   204.83990849  241.50676742  278.1463033
   314.75854395  351.34352797  387.90126959  424.43182079  460.93520112
   497.41144089  206.80721015  243.06086611  279.28781071  315.4880708
   351.66168384  387.80866326  423.92905978  460.02289204  496.09018936
   208.73072598  244.58038815  280.40393034  316.20137845  351.9727689
   387.71811431  423.43746419  459.13083635  494.79825914]
 [ 426.8121718   428.32143334  429.8295305   431.33646451  432.84223704
   434.34684879  435.85030196  437.35259747  438.85373664  462.05637953
   463.53462764  465.01174858  466.4877435   467.96261404  469.43636081
   470.90898598  472.38049038  473.8508753   496.48908231  497.93733677
   499.38449962  500.83057199  502.27555543  503.71945052  505.16225935
   506.60398272  508.04462186  530.13798628  531.55722173  532.9753996
   534.39252098  535.80858736  537.22359928  538.63755877  540.05046658
   541.46232388  563.02956014  564.42070856  565.81083199  567.19993146
   568.58800842  569.97506337  571.36109827  572.74611383  574.13011117
   595.18907294  596.553026    597.9159853   599.2779518   600.63892691
   601.99891109  603.35790623  604.71591302  606.07293252]]
```

**Comment by miguelriemoliveira** [comment]
Ok, I think the problem is that the pinhole camera model from ros uses the camera_info message, in particular the **P** matrix (where we use the **K** matrix).

Our camera info message is:

```
header: 
  seq: 8737
  stamp: 
    secs: 1575573625
    nsecs: 261431128
  frame_id: "top_left_camera_optical"
height: 724
width: 964
distortion_model: "plumb_bob"
D: [-0.106194, -0.182228, 0.000962, 0.00563, 0.0]
K: [1167.914995, 0.0, 505.998418, 0.0, 1178.789838, 375.348091, 0.0, 0.0, 1.0]
R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
P: [1137.186279, 0.0, 511.388126, 0.0, 0.0, 1164.459229, 376.080715, 0.0, 0.0, 0.0, 1.0, 0.0]
binning_x: 1
binning_y: 1
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: True
```

which shows that **K** and **P** are not the same. From what I read [here](http://docs.ros.org/melodic/api/sensor_msgs/html/msg/CameraInfo.html) they should have P[1:3,1:3] = K, and this does not happen. Here's a transcript:

```
# Projection/camera matrix
#     [fx'  0  cx' Tx]
# P = [ 0  fy' cy' Ty]
#     [ 0   0   1   0]
# By convention, this matrix specifies the intrinsic (camera) matrix
#  of the processed (rectified) image. That is, the left 3x3 portion
#  is the normal camera intrinsic matrix for the rectified image.
# It projects 3D points in the camera coordinate frame to 2D pixel
#  coordinates using the focal lengths (fx', fy') and principal point
#  (cx', cy') - these may differ from the values in K.
# For monocular cameras, Tx = Ty = 0. Normally, monocular cameras will
#  also have R = the identity and P[1:3,1:3] = K.
# For a stereo pair, the fourth column [Tx Ty 0]' is related to the
#  position of the optical center of the second camera in the first
#  camera's frame. We assume Tz = 0 so both cameras are in the same
#  stereo image plane. The first camera always has Tx = Ty = 0. For
#  the right (second) camera of a horizontal stereo pair, Ty = 0 and
#  Tx = -fx' * B, where B is the baseline between the cameras.
# Given a 3D point [X Y Z]', the projection (x, y) of the point onto
#  the rectified image is given by:
#  [u v w]' = P * [X Y Z 1]'
#         x = u / w
#         y = v / w
```

**Comment by miguelriemoliveira** [comment]
I've checked and this comes directly from the bag file ...

```
header: 
  seq: 8606
  stamp: 
    secs: 1575573615
    nsecs: 904111054
  frame_id: "top_left_camera_optical"
height: 724
width: 964
distortion_model: "plumb_bob"
D: [-0.1061939203056552, -0.1822283296790906, 0.0009618795250864933, 0.005629828605426035, 0.0]
K: [1167.91499518757, 0.0, 505.9984183682733, 0.0, 1178.789838034347, 375.3480910015082, 0.0, 0.0, 1.0]
R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
P: [1137.186279296875, 0.0, 511.3881260477501, 0.0, 0.0, 1164.459228515625, 376.0807154139911, 0.0, 0.0, 0.0, 1.0, 0.0]
binning_x: 1
binning_y: 1
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: True
```
